[package]
name = "dashcore"
version = "0.29.1"
authors = ["Samuel Westrich <sam@dash.org>", "Anton Suprunchuk <anton@dash.org>"]
license = "CC0-1.0"
homepage = "https://github.com/dashevo/rust-dashcore/"
repository = "https://github.com/dashevo/rust-dashcore/"
documentation = "https://dashcore.readme.io/docs"
description = "General purpose library for using and interoperating with Dash Core payment chain."
keywords = [ "crypto", "dash" ]
readme = "README.md"
exclude = ["./test_data"]

# Please don't forget to add relevant features to docs.rs below
[features]
default = [ "std", "secp-recovery", "hex" ]
base64 = [ "base64-compat" ]
unstable = []
rand = ["secp256k1/rand-std"]
use-serde = ["serde", "bitcoin_hashes/serde", "secp256k1/serde"]
secp-lowmemory = ["secp256k1/lowmemory"]
secp-recovery = ["secp256k1/recovery"]
signer = ["secp-recovery", "rand", "anyhow"]

# At least one of std, no-std must be enabled.
#
# The no-std feature doesn't disable std - you need to turn off the std feature for that by disabling default.
# Instead no-std enables additional features required for this crate to be usable without std.
# As a result, both can be enabled without conflict.
std = ["secp256k1/std", "bitcoin_hashes/std", "bech32/std"]
no-std = ["hashbrown", "core2/alloc", "bitcoin_hashes/alloc", "secp256k1/alloc"]

[package.metadata.docs.rs]
features = [ "std", "secp-recovery", "base64", "rand", "use-serde", "bitcoinconsensus", "signer"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
bech32 = { version = "0.8.1", default-features = false }
bitcoin_hashes = { version = "0.10.0", default-features = false }
secp256k1 = { git = "https://github.com/rust-bitcoin/rust-secp256k1", default-features = false, rev="f7cae46fc7733522cb84ef1b1ee1d1ed0cec2fd3" }
core2 = { version = "0.3.0", optional = true, default-features = false }

base64-compat = { version = "1.0.0", optional = true }
bitcoinconsensus = { version = "0.19.0-3", optional = true }
serde = { version = "1", features = [ "derive" ], optional = true }
hashbrown = { version = "0.8", optional = true }

anyhow = { version= "1.0", optional = true}
hex = { version= "0.4", optional = true}

[dev-dependencies]
serde_json = "<1.0.45"
serde_test = "1"
secp256k1 = { git = "https://github.com/rust-bitcoin/rust-secp256k1", features = [ "recovery", "rand-std" ], rev="f7cae46fc7733522cb84ef1b1ee1d1ed0cec2fd3" }
bincode = "1.3.1"
# We need to pin ryu (transitive dep from serde_json) to stay compatible with Rust 1.22.0
ryu = "<1.0.5"
bip39 = "1.0.1"
hex = "0.4"

[[example]]
name = "bip32"

[[example]]
name = "handshake"
required-features = ["std"]
